version: '3'

volumes:
  django_sample_db_dev: {}

services:
  db:
    image: postgres
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:postgres
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh postgres:5432 -t 10
        python manage.py migrate
        python manage.py runserver 0:8000
    volumes:
      - ./:/app/
